name: Nix - Lint
description: Run nixfmt on a flake directory

inputs:
    project_dir:
        description: Directory containing flake.nix
        required: true

runs:
    using: composite
    steps:
        - name: Check Nixfmt
          shell: bash
          working-directory: ${{ inputs.project_dir }}
          run: |
              set -euo pipefail
              
              files=$(find . -name "*.nix")
              
              if [ -z "$files" ]; then
                 echo "No .nix files found in ${{ inputs.project_dir }}"
                 exit 0
              fi
              
              failures=0
              
              for file in $files; do
                 if nix run nixpkgs#nixfmt-rfc-style -- --check --indent=4 "$file" >/dev/null 2>/dev/null; then
                    echo "  ✓ $file"
                 else
                    echo "  ✗ $file"
                    failures=$((failures+1))
                 fi
              done
              
              if [ "$failures" -ne 0 ]; then
                 echo "❌ $failures files failed linting."
                 exit 1
              fi