name: Upload file
description: Upload a file to a KestrelsDevelopment/FileApi
author: AceOfKestrels

inputs:
    url:
        description: "The URL to upload to"
        required: true
    file-path:
        description: "The path of the file to upload"
        required: true
    api-key:
        description: The PSK used for authentication
        required: true

outputs:
    download-url:
        description: "The url the file can be downloaded from"
        value: ${{ steps.upload.outputs.download-url }}
    checksum:
        description: "The checksum of the uploaded file"
        value: ${{ steps.upload.outputs.checksum }}

runs:
    using: composite
    steps: 
      - name: "Upload file"
        id: "upload"
        shell: bash
        env:
            FILE_API_KEY: ${{ inputs.api-key }}
            UPLOAD_URL: ${{ inputs.url }}
            FILE_PATH: ${{ inputs.file-path }}
        run: | 
            set -euo pipefail

            checksum=$(sha256sum -- "$FILE_PATH" | awk '{print $1}')
            echo "checksum=$checksum" >> "$GITHUB_OUTPUT"

            curl -sS -f -v -X POST "$UPLOAD_URL/upload" \
                -H "Authorization: Bearer $FILE_API_KEY" \
                -H "Checksum: $checksum" \
                -F "file=@$FILE_PATH"

            echo "download-url=$UPLOAD_URL/download" >> "$GITHUB_OUTPUT"
