name: NuGet - Generate Pack Matrix
description: Discover packable csproj files and emit a build matrix
inputs:
  projects_glob:
    description: Glob for projects (can be multiline)
    required: true
  exclude_glob:
    description: Glob(s) to exclude (can be multiline)
    required: true
outputs:
  matrix:
    description: JSON matrix for strategy
    value: ${{ steps.gen.outputs.matrix }}
runs:
  using: composite
  steps:
    - id: gen
      shell: bash
      env:
        PROJECTS_GLOB: ${{ inputs.projects_glob }}
        EXCLUDE_GLOB: ${{ inputs.exclude_glob }}
      run: |
        set -euo pipefail
        shopt -s globstar nullglob extglob
        if ! command -v jq >/dev/null 2>&1; then
          sudo apt-get update -y
          sudo apt-get install -y jq
        fi
        mapfile -t project_patterns < <(printf '%s\n' $PROJECTS_GLOB)
        echo project_patterns
        mapfile -t exclude_patterns < <(printf '%s\n' $EXCLUDE_GLOB)
        echo exclude_patterns
        include=()
        for pat in "${project_patterns[@]}"; do
          for f in $pat; do
            [[ -f "$f" ]] || continue
            [[ "$f" == *.csproj ]] || continue
            skip=false
            for ex in "${exclude_patterns[@]}"; do
              [[ -z "$ex" ]] && continue
              if [[ "$f" == $ex ]]; then
                skip=true
                break
              fi
            done
            $skip && continue
            if grep -Eq '<IsPackable>\s*false\s*</IsPackable>' "$f"; then
              continue
            fi
            include+=( "$f" )
          done
        done
        if (( ${#include[@]} == 0 )); then
          echo 'matrix={"include":[]}' >> "$GITHUB_OUTPUT"
          exit 0
        fi
        json=$(jq -n --argjson arr "$(printf '%s\n' "${include[@]}" | jq -R . | jq -s .)" '
          { include:
              ( $arr
                | map({
                    project: .,
                    project_dir: ( . | sub("/[^/]+$"; "") )
                  })
              )
          }')

        echo "matrix=$json" >> "$GITHUB_OUTPUT"

    - name: Matrix generated
      shell: bash
      run: echo "Matrix generated."
