name: Parse nix files
description: Attempt to parse all .nix files in the repository.
author: AceOfKestrels

inputs:
  project_dir:
    description: Directory containing flake.nix
    required: true

runs:
  using: composite
  steps:
    - name: Check Flakes
      shell: bash
      working-directory: ${{ inputs.project_dir }}
      env:
        NIX_CONFIG: "experimental-features = nix-command flakes"
      run: |
        set -euo pipefail
        if ! nix flake update; then
            echo "  ✗ failed to update lock file"
            exit 1
        fi
