name: NuGet - Build
description: dotnet build with CI flags
inputs:
  project:
    description: Path to csproj
    required: true
  configuration:
    description: Build configuration
    required: true
    default: Release
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        dotnet build "${{ inputs.project }}" \
          -c "${{ inputs.configuration }}" \
          --no-restore \
          -p:ContinuousIntegrationBuild=true
