# .github/actions/nuget-test/action.yml
name: NuGet - Test
description: Discover and run tests
inputs:
  project:
    description: Path to csproj
    required: true
  configuration:
    description: Build configuration
    required: true
    default: Release
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if grep -q "Microsoft.NET.Test.Sdk" "${{ inputs.project }}"; then
            echo "Test project found!"
        elif grep -q "TUnit" "${{ inputs.project }}"; then
            echo "Test project found!"
        else
            echi "Not a test project. Skipping..."
            exit 0
        fi

        dotnet run "${{ inputs.project }}" \
          -c "${{ inputs.configuration }}" \
          --no-restore \
          -p:ContinuousIntegrationBuild=true
