# .github/actions/nuget-test/action.yml
name: NuGet - Test
description: Discover and run tests
inputs:
  configuration:
    description: Build configuration
    required: true
    default: Release
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -e
        shopt -s globstar nullglob
        tests=( **/*[Tt]est*.csproj )
        if (( ${#tests[@]} )); then
          dotnet test -c "${{ inputs.configuration }}" --no-build --logger trx --results-directory TestResults
        else
          echo "No test projects found. Skipping."
        fi
